### PR TITLE
adds font size slider, makes display options use flex fix #95

### LINKED ISSUE #95: font size controls in control panel
user report

I am using SikhiToThe Max for more than 8 years. Have been less frequent recently due to availability of Android apps. 
However, found the new look as really amazing and useful. Please give and option to increase/decrease the font size or the shabad display area
WJKK WJKF,
Gurpreet Singh

### PR DESCRIPTION
**Pull request by ManjotS**

### CODE REVIEW

**Comment by ManjotS** [comment]
dont merge yet, need to add prefs

**Comment by tarunsingh5** [comment]
slider doesn't work on mobile

**Comment by ManjotS** [comment]
how did you test it @tarunsingh5

**Comment by ManjotS** [comment]
@navdeepsinghkhalsa ready for review/merge

**Pull request merged**
