### PR TITLE
Update renderGurmukhiKeyboard.js

### PR DESCRIPTION
**Pull request by tarunsingh5**
should be ready to merge

### CODE REVIEW

**Comment by tarunsingh5** [comment]
#211 gets fixed by this

**Comment by bogas04** [comment]
Awesome.

Could you please take time to convert that minor jQuery code to vanilla JS one?

```diff
- $("#abc").hide();
+ document.querySelector("#abc").style.display = 'block';
```

We would lose some animation but it'll help us in future while porting.

@navdeepsinghkhalsa what do you think?

**Comment by tarunsingh5** [comment]
@bogas04  - that actually breaks the keyboard - i think we should get it fixed first and then we can optimize later

**Comment by bogas04** [comment]
Sure!

**Comment by navdeepsinghkhalsa** [comment]
I agree with @bogas04. We should avoid technical debt.

**Comment by tarunsingh5** [comment]
Ok, I can't get it to work the way @bogus04 suggested. Please edit.

**Pull request merged**
