### PR TITLE
Migrate to React + Webpack

### PR DESCRIPTION
**Pull request by bogas04**
Fix for #70 

* [x]  Passed [sanity tests](http://bit.ly/sttm-sanity-tests).
* [x]  Ran `npm test` & fixed newly introduced lint errors.
* [x]  Checked console for errors.

<!-- New to markdown? Simply put an 'x' between [ ] to check it. Like [x] this. (No spaces).

### CODE REVIEW

**Comment by bogas04** [comment]
* [ ] About, ToS and Hukamnama page have weird width on mobile.

**Comment by ManjotS** [comment]
split view padding needs to match prod
image

**Comment by ManjotS** [comment]
font and margin issue:
image

**Comment by ManjotS** [comment]
other than above issues, approved by @tarunsingh5

**Comment by bogas04** [comment]
* [x] Use Next/Previous page instead of Load More.
* [x] Fix #340

**Comment by ManjotS** [comment]
@tarunsingh5 waiting for your yes

**Pull request merged**
