### PR TITLE
Move served files to public folder

### PR DESCRIPTION
**Pull request by bogas04**
Right now we end up serving our server files as well (VERY BAD).

This change would mitigate that.

### CODE REVIEW

**Comment by bogas04** [comment]
@plug-n-play I created the PR so as to discuss what's missing.

You'll also have to move

```
/
- embed.js ➡️ public/embed.js
- favicon.ico ➡️ public/favicon.ico
- ieconfig.xml ➡️ public/ieconfig.xml
- manifest.json ➡️ public/manifest.json
- service-worker.js ➡️ public/service-worker.js
```

**Comment by plug-n-play** [comment]
Done - please check

**Comment by bogas04** [comment]
Could you please go through bit.ly/sttm-sanity-tests with network panel open to see if there's anything 404 being caused due to this.

**Comment by plug-n-play** [comment]
Done. All looks good. Here is the summary - https://docs.google.com/spreadsheets/d/1PiWOFvANDLMvGo3JnspTqXoaLlAUbhpYiNedQRNE9Uc/edit#gid=0

**Comment by bogas04** [comment]
Awesome. Congratulations on your second PR. :D 

I hope by this time you've gotten a good sense of the project and are able to read through the issues and pick any.

Also, you can use markdown for sharing status/report as it's easier for reviewers to go through it. Unless it's very huge obviously.

**Pull request merged**
