### PR TITLE
Use JSX 

### PR DESCRIPTION
**Pull request by bogas04**
The plan is like this:

Phase 1 (this PR):
* [ ] migrate from `h()` to `JSX` with use of `babel-plugin-transform-react-jsx`.
* [ ] restructure codebase to use `webpack`. Abstract out components and utils.

Phase 2:
* [ ] migrate to usage of `ReactJS`. It will become very easy with Phase 1 completed.
* [ ] refactor remaining code that relies on global variables, DOM mutations via jQuery.

### CODE REVIEW

**Comment by bogas04** [comment]
Don't review just yet, I'm yet to restructure and refactor the code.

**Comment by ManjotS** [comment]
Can we be careful not to introduce regressions please? (ie toggle issue) if you are going to make a massive change, make sure everything is changed that needs to be.

**Comment by bogas04** [comment]
Definitely, this is a long term patch, and others would be rebased.

**Comment by navdeepsinghkhalsa** [comment]
Sorry it took so long for me to check this. @bogas04 Could you please resolve conflicts? Then I will review

**Comment by bogas04** [comment]
Creating a new PR

**Pull request closed without merging**
